services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      - DATABASE_URL=postgresql://admin:password@db/library

  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d library"]
      interval: 10s
      timeout: 5s
      retries: 5
